### ISSUE TITLE
workspace saga tests are failing

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet-frontend#698]
```
 FAIL  src\sagas\__tests__\workspaces.ts (18.17s)
  ● PLAYGROUND_EXTERNAL_SELECT › puts changePlaygroundExternal, beginClearContext, clearReplOutput and calls showSuccessMessage correctly

    SagaTestError:
    put expectation unmet:

    Expected
    --------
    { '@@redux-saga/IO': true,
      combinator: false,
      type: 'PUT',
      payload:
       { channel: undefined,
         action:
          { type: 'CHANGE_PLAYGROUND_EXTERNAL',
            payload: { newExternal: undefined } } } }


      at new SagaTestError (node_modules/redux-saga-test-plan/lib/shared/SagaTestError.js:17:57)
      at node_modules/redux-saga-test-plan/lib/expectSaga/expectations.js:67:13
      at node_modules/redux-saga-test-plan/lib/expectSaga/index.js:563:7
          at Array.forEach (<anonymous>)
      at checkExpectations (node_modules/redux-saga-test-plan/lib/expectSaga/index.js:562:18)

  ● BEGIN_CLEAR_CONTEXT › loads TWO_DIM_RUNES library correctly

    expect(jest.fn()).toHaveBeenCalledWith(expected)

    Expected mock function to have been called with:
      ["TWO_DIM_RUNES"]
    But it was not called.

      513 |       .silentRun()
      514 |       .then(() => {
    > 515 |         expect(loadLib).toHaveBeenCalledWith('TWO_DIM_RUNES');
      516 |         expect(getReadyWebGLForCanvas).toHaveBeenCalledWith('2d');
      517 |         globals.forEach(item => {
      518 |           expect(window[item[0]]).toEqual(item[1]);

      at redux_saga_test_plan_1.expectSaga.put.dispatch.silentRun.then (src/sagas/__tests__/workspaces.ts:515:25)

  ● BEGIN_CLEAR_CONTEXT › loads THREE_DIM_RUNES library correctly

    expect(jest.fn()).toHaveBeenCalledWith(expected)

    Expected mock function to have been called with:
      ["THREE_DIM_RUNES"]
    But it was not called.

      542 |       .silentRun()
      543 |       .then(() => {
    > 544 |         expect(loadLib).toHaveBeenCalledWith('THREE_DIM_RUNES');
      545 |         expect(getReadyWebGLForCanvas).toHaveBeenCalledWith('3d');
      546 |         globals.forEach(item => {
      547 |           expect(window[item[0]]).toEqual(item[1]);

      at redux_saga_test_plan_1.expectSaga.put.dispatch.silentRun.then (src/sagas/__tests__/workspaces.ts:544:25) FAIL  src\sagas\__tests__\workspaces.ts (18.17s)
  ● PLAYGROUND_EXTERNAL_SELECT › puts changePlaygroundExternal, beginClearContext, clearReplOutput and calls showSuccessMessage correctly

    SagaTestError:
    put expectation unmet:

    Expected
    --------
    { '@@redux-saga/IO': true,
      combinator: false,
      type: 'PUT',
      payload:
       { channel: undefined,
         action:
          { type: 'CHANGE_PLAYGROUND_EXTERNAL',
            payload: { newExternal: undefined } } } }


      at new SagaTestError (node_modules/redux-saga-test-plan/lib/shared/SagaTestError.js:17:57)
      at node_modules/redux-saga-test-plan/lib/expectSaga/expectations.js:67:13
      at node_modules/redux-saga-test-plan/lib/expectSaga/index.js:563:7
          at Array.forEach (<anonymous>)
      at checkExpectations (node_modules/redux-saga-test-plan/lib/expectSaga/index.js:562:18)

  ● BEGIN_CLEAR_CONTEXT › loads TWO_DIM_RUNES library correctly

    expect(jest.fn()).toHaveBeenCalledWith(expected)

    Expected mock function to have been called with:
      ["TWO_DIM_RUNES"]
    But it was not called.

      513 |       .silentRun()
      514 |       .then(() => {
    > 515 |         expect(loadLib).toHaveBeenCalledWith('TWO_DIM_RUNES');
      516 |         expect(getReadyWebGLForCanvas).toHaveBeenCalledWith('2d');
      517 |         globals.forEach(item => {
      518 |           expect(window[item[0]]).toEqual(item[1]);

      at redux_saga_test_plan_1.expectSaga.put.dispatch.silentRun.then (src/sagas/__tests__/workspaces.ts:515:25)

  ● BEGIN_CLEAR_CONTEXT › loads THREE_DIM_RUNES library correctly

    expect(jest.fn()).toHaveBeenCalledWith(expected)

    Expected mock function to have been called with:
      ["THREE_DIM_RUNES"]
    But it was not called.

      542 |       .silentRun()
      543 |       .then(() => {
    > 544 |         expect(loadLib).toHaveBeenCalledWith('THREE_DIM_RUNES');
      545 |         expect(getReadyWebGLForCanvas).toHaveBeenCalledWith('3d');
      546 |         globals.forEach(item => {
      547 |           expect(window[item[0]]).toEqual(item[1]);

      at redux_saga_test_plan_1.expectSaga.put.dispatch.silentRun.then (src/sagas/__tests__/workspaces.ts:544:25)
```

**Comment by rrtheonlyone** [comment]
Yup this is because the library names are changed. I can take a look.
